CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50),
	CPF VARCHAR(11) NOT NULL,
	RG VARCHAR(15),
	EMAIL VARCHAR(50),
	LOGIN VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	CEP VARCHAR(15),
	RUA VARCHAR(70),
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(20),
	CIDADE VARCHAR(20),
	UF VARCHAR(20),
	NUMERO VARCHAR(20)
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE);

CREATE SEQUENCE SQ_CLIENTE START WITH 1 CACHE 10;