CREATE TABLE COMBO(
	ID_COMBO NUMBER NOT NULL,
	ID_EMPRESA NUMBER NOT NULL,
	NOME VARCHAR(60) NOT NULL,
	DESCRICAO VARCHAR(255),
	VALOR_UNITARIO NUMBER(8,2)
);

ALTER TABLE COMBO ADD CONSTRAINT PK_COMBO PRIMARY KEY(ID_COMBO);
ALTER TABLE COMBO ADD CONSTRAINT FK_EMPRES_COMBO FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA);

CREATE SEQUENCE SQ_COMBO START WITH 1 CACHE 10;
