CREATE TABLE EMPRESA(
	ID_EMPRESA NUMBER NOT NULL,
	RAZAO_SOCIAL VARCHAR(50) NOT NULL,
	CNPJ VARCHAR(50) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	CEP VARCHAR(15),
	RUA VARCHAR(70),
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(20),
	CIDADE VARCHAR(20),
	UF VARCHAR(20),
	NUMERO VARCHAR(20)
);

ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY(ID_EMPRESA);

CREATE SEQUENCE SQ_EMPRESA START WITH 1 CACHE 10;