CREATE TABLE PEDIDO(
	ID_PEDIDO NUMBER NOT NULL,
	ID_COMBO NUMBER NOT NULL,
	ID_CLIENTE NUMBER NOT NULL,
	VALOR_TOTAL NUMBER(10, 2) NOT NULL,
	STATUS VARCHAR(50) NOT NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_COMBO FOREIGN KEY(ID_COMBO) REFERENCES COMBO(ID_COMBO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

CREATE SEQUENCE SQ_PEDIDO START WITH 1 CACHE 10;